# Generated by Django 4.1.3 on 2023-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
