# Generated by Django 4.1.3 on 2023-11-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_items_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='stocks',
        ),
    ]
